-- Copyright (c) 2013 VMware, Inc. All rights reserved. 
-- ------------------------
-- 'PERSISTENT' DISK STORE 
-- ------------------------

CREATE DISKSTORE PERSISTENT1 
    MAXLOGSIZE 1024 
    AUTOCOMPACT TRUE
    ALLOWFORCECOMPACTION  FALSE 
    COMPACTIONTHRESHOLD  70
    WRITEBUFFERSIZE 32768;

-- ----------------------
-- 'OVERFLOW' DISK STORE 
-- ----------------------
CREATE DISKSTORE OVERFLOW1 
    MAXLOGSIZE 1024 
    AUTOCOMPACT TRUE
    ALLOWFORCECOMPACTION  FALSE 
    COMPACTIONTHRESHOLD  70
    WRITEBUFFERSIZE 32768;

-- -----------------------------
-- 'ASYNCEVENT' DISK STORE 
-- -----------------------------
CREATE DISKSTORE ASYNCEVENT1 
    MAXLOGSIZE 1024 
    AUTOCOMPACT TRUE
    ALLOWFORCECOMPACTION  FALSE 
    COMPACTIONTHRESHOLD  70
    WRITEBUFFERSIZE 32768;
